#include "mmi2c.h"
#include "ti_msp_dl_config.h"

/* Replace these names with the names generated by your SysConfig file. */
#define APP_I2C_INST I2C_0_INST
#define APP_I2C_IRQN I2C_0_INST_INT_IRQN

static mmi2c_t g_i2c;
static volatile uint32_t g_microseconds;

/* Drive this from a 1 MHz timer ISR (or replace it with your own timer read). */
static uint32_t app_now_us(void *unused)
{
    (void) unused;
    return g_microseconds;
}

/* Board-specific hook. Implement this sequence using the actual GPIOs/timer:
 * 1. Keep EN low; switch PCA9615 VDD(B) on.
 * 2. Wait at least 11 ms (12 ms recommended margin).
 * 3. Drive EN high.
 * 4. Allow at least the 100 us bus-idle qualification plus margin.
 * Return false if the timeout cannot accommodate the complete sequence. */
static bool app_bridge_acquire(void *unused, uint32_t timeout_us)
{
    (void) unused;
    (void) timeout_us;
    return true;
}

/* Board-specific hook: drive EN low first, then switch VDD(B) off. The library
 * calls this only after the MSPM0 reports IDLE and bus-not-busy. */
static void app_bridge_release(void *unused)
{
    (void) unused;
}

void I2C_0_INST_IRQHandler(void)
{
    mmi2c_handle_irq(&g_i2c);
}

int main(void)
{
    SYSCFG_DL_init();

    mmi2c_config_t config = {
        .now_us                    = app_now_us,
        .bridge_acquire            = app_bridge_acquire,
        .bridge_release            = app_bridge_release,
        .bus_recover               = NULL,
        .user                      = NULL,
        .bus_idle_timeout_us       = 5000u,
        .transfer_timeout_us       = 2000u,
        .bridge_ready_timeout_us   = 15000u,
        .rx_done_settle_us         = 2u,
        .random_seed               = 0x12345678u, /* Use unique module ID. */
        .backoff_slot_us           = 250u,
        .max_arbitration_retries   = 8u,
        .max_nack_retries          = 0u,
        .release_bridge_when_done  = true,
    };

    (void) mmi2c_init(&g_i2c, APP_I2C_INST, &config);
    NVIC_EnableIRQ(APP_I2C_IRQN);

    uint8_t message[MMI2C_MAX_MESSAGE_BYTES] = {
        0xA5u, 0x01u, 0x12u, 0x34u, 0x56u, 0x78u, 0x9Au, 0xBCu};
    mmi2c_transfer_t transfer = {
        .address   = 0x42u,
        .tx_data   = message,
        .rx_data   = NULL,
        .tx_length = sizeof(message),
        .rx_length = 0u,
    };
    (void) mmi2c_submit(&g_i2c, &transfer);

    for (;;) {
        mmi2c_process(&g_i2c);
        if (mmi2c_get_result(&g_i2c) != MMI2C_RESULT_IN_PROGRESS) {
            mmi2c_result_t result = mmi2c_take_result(&g_i2c);
            (void) result; /* Hand result to the application state machine. */
        }
        __WFI();
    }
}
